# Generated by Django 4.0.3 on 2022-03-27 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upcomingalbumentrymodel',
            options={'ordering': ['release_date']},
        ),
        migrations.AlterField(
            model_name='upcomingalbumentrymodel',
            name='release_date',
            field=models.DateField(default=datetime.date(2022, 3, 27)),
        ),
    ]
