# Generated by Django 4.0.3 on 2022-03-28 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_alter_upcomingalbumentrymodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingalbumentrymodel',
            name='release_date',
            field=models.DateField(default=datetime.date(2022, 3, 28)),
        ),
    ]
