# Generated by Django 4.0.3 on 2022-03-28 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_songmodel_remove_song_album_remove_song_artist_and_more'),
        ('profile_page', '0003_alter_listenedsongsmodel_song'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Song',
        ),
        migrations.AddField(
            model_name='songmodel',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', related_query_name='song', to='main_page.albummodel'),
        ),
        migrations.AddField(
            model_name='songmodel',
            name='artist',
            field=models.ManyToManyField(related_name='songs', related_query_name='song', to='main_page.artistmodel'),
        ),
    ]
