# Generated by Django 4.0.3 on 2022-03-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_alter_albummodel_release_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='songmodel',
            name='spotify_id',
            field=models.CharField(default='5mc6EyF1OIEOhAkD0Gg9Lc', max_length=50, unique=True),
        ),
    ]
