# Generated by Django 4.0.3 on 2022-04-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0016_alter_upcomingalbumentrymodel_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='albummodel',
            name='total_tracks',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='songmodel',
            name='song_position',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
