# Generated by Django 4.0.3 on 2022-04-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0017_albummodel_total_tracks_songmodel_song_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songmodel',
            old_name='song_position',
            new_name='track_number',
        ),
        migrations.AddField(
            model_name='albummodel',
            name='album_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
