# Generated by Django 4.0.3 on 2022-04-08 10:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0019_alter_upcomingalbumentrymodel_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingalbumentrymodel',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_page.albummodel'),
        ),
        migrations.AlterField(
            model_name='upcomingalbumentrymodel',
            name='release_date',
            field=models.DateField(default=datetime.date(2022, 4, 8)),
        ),
    ]
