# Generated by Django 4.0.3 on 2022-04-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0023_alter_upcomingalbumentrymodel_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistmodel',
            name='genres',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
