# Generated by Django 4.0.3 on 2022-04-20 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0025_alter_upcomingalbumentrymodel_release_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='songmodel',
            options={'ordering': ['album', 'track_number'], 'verbose_name': 'Song', 'verbose_name_plural': 'Songs'},
        ),
        migrations.AlterField(
            model_name='upcomingalbumentrymodel',
            name='release_date',
            field=models.DateField(default=datetime.date(2022, 4, 20)),
        ),
    ]
