# Generated by Django 4.0.3 on 2022-04-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0029_alter_artistmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingalbumentrymodel',
            name='release_date',
            field=models.DateField(),
        ),
    ]
