# Generated by Django 4.0.3 on 2022-04-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0030_alter_upcomingalbumentrymodel_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albummodel',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
