# Generated by Django 4.0.3 on 2022-04-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0031_alter_albummodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songmodel',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
