# Generated by Django 4.0.3 on 2022-06-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0035_albummodel_spotify_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albummodel',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='artistmodel',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='upcomingalbumentrymodel',
            name='album_name',
            field=models.CharField(max_length=50),
        ),
    ]
