# Generated by Django 4.0.3 on 2022-04-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0007_alter_spotifyprofile_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyprofile',
            name='spotify_id',
            field=models.CharField(default='31j4giorrbc42l75uzemzvo3xrgi', max_length=100),
            preserve_default=False,
        ),
    ]
