# Generated by Django 4.0.3 on 2022-03-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='bio',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='pfp',
            field=models.ImageField(default='default_pfp.png', upload_to=''),
        ),
    ]
