# Generated by Django 4.0.3 on 2022-03-28 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_songmodel_remove_song_album_remove_song_artist_and_more'),
        ('profile_page', '0002_alter_profilemodel_bio_alter_profilemodel_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listenedsongsmodel',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', related_query_name='user', to='main_page.songmodel'),
        ),
    ]
