# Generated by Django 4.0.3 on 2022-03-28 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_delete_song_songmodel_album_songmodel_artist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile_page', '0003_alter_listenedsongsmodel_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListenedAlbumModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listened_users', related_query_name='listened_user', to='main_page.albummodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listened_albums', related_query_name='listened_album', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
