# Generated by Django 4.0.3 on 2022-03-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0004_listenedalbummodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='listenedsongsmodel',
            name='played_at',
            field=models.CharField(default='bruh', max_length=20),
        ),
    ]
