# Generated by Django 4.0.3 on 2022-03-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0006_reviewmodel_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='recommended',
            field=models.BooleanField(null=True),
        ),
    ]
