# Generated by Django 4.0.3 on 2022-03-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0007_reviewmodel_recommended'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listenedsongsmodel',
            options={'ordering': ['played_at']},
        ),
        migrations.AlterField(
            model_name='listenedsongsmodel',
            name='played_at',
            field=models.CharField(default='bruh', max_length=20, unique=True),
        ),
    ]
