# Generated by Django 4.0.3 on 2022-03-31 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0008_alter_listenedsongsmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listenedalbummodel',
            options={'ordering': ['album']},
        ),
        migrations.AddField(
            model_name='likemodel',
            name='visible',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listenedalbummodel',
            name='visible',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listenedsongsmodel',
            name='played_at',
            field=models.CharField(default='bruh', max_length=20),
        ),
    ]
