# Generated by Django 4.0.3 on 2022-04-02 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0014_alter_upcomingalbumentrymodel_release_date'),
        ('profile_page', '0010_waitinglistalbummodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='favorite_album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_page.albummodel'),
        ),
    ]
