# Generated by Django 4.0.3 on 2022-04-04 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_page', '0015_alter_upcomingalbumentrymodel_release_date'),
        ('profile_page', '0011_profilemodel_favorite_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_users', related_query_name='recommendation_user', to='main_page.albummodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_albums', related_query_name='recommendation_album', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['album'],
            },
        ),
    ]
