# Generated by Django 4.0.3 on 2022-04-04 22:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_page', '0016_alter_upcomingalbumentrymodel_release_date'),
        ('profile_page', '0013_alter_listenedalbummodel_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListenedAlbumModel',
            new_name='EncounteredAlbumModel',
        ),
    ]
