# Generated by Django 4.0.3 on 2022-04-05 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0017_albummodel_total_tracks_songmodel_song_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile_page', '0014_rename_listenedalbummodel_encounteredalbummodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounteredalbummodel',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encountered_users', related_query_name='encountered_user', to='main_page.albummodel'),
        ),
        migrations.AlterField(
            model_name='encounteredalbummodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encountered_albums', related_query_name='encountered_album', to=settings.AUTH_USER_MODEL),
        ),
    ]
