# Generated by Django 4.0.3 on 2022-04-06 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0019_alter_upcomingalbumentrymodel_release_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile_page', '0015_alter_encounteredalbummodel_album_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifySavedAlbumModerl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SpotifyUserSaved', to='main_page.albummodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SpotifySavedAlbum', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpotifyLikeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SpotifyUserLiked', to='main_page.songmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SpotifyLike', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
