# Generated by Django 4.0.3 on 2022-04-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0016_spotifysavedalbummoderl_spotifylikemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounteredalbummodel',
            name='completion',
            field=models.SmallIntegerField(default=0),
        ),
    ]
