# Generated by Django 4.0.3 on 2022-04-08 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0017_encounteredalbummodel_completion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encounteredalbummodel',
            options={'ordering': ['completion']},
        ),
    ]
