# Generated by Django 4.0.3 on 2022-04-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0018_alter_encounteredalbummodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounteredalbummodel',
            name='songs_count',
            field=models.SmallIntegerField(default=0),
        ),
    ]
