# Generated by Django 4.0.3 on 2022-04-10 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0022_alter_upcomingalbumentrymodel_release_date'),
        ('profile_page', '0021_alter_profilemodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='encountered_visibility',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='likes_visibility',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='playlist_albums',
            field=models.ManyToManyField(blank=True, null=True, to='main_page.albummodel'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='favorite_album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fav_album', to='main_page.albummodel'),
        ),
    ]
