# Generated by Django 4.0.3 on 2022-06-01 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0033_albummodel_album_songs_sting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile_page', '0024_alter_listenedsongsmodel_played_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyFollowedArtistModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SpotifyFollowedArtist', to='main_page.artistmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SpotifyFollowedArtist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
