# Generated by Django 4.0.3 on 2022-06-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0025_spotifyfollowedartistmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounteredalbummodel',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
